route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token: '7596665134:AAEeN9kn2imlPbiR8M6umgPOFq1bKdoRtUo'
      api_url: "https://api.telegram.org"
      chat_id: -1002376975407
      parse_mode: 'MarkdownV2'
      send_resolved: true
      message: |
        🚨 *Alert*: `{{ .CommonLabels.alertname }}`
        *Instance*: `{{ .CommonLabels.instance }}`
        *Status*: `{{ .Status | toUpper }}`
  - name: 'sms'
    webhook_configs:
      - url: 'http://127.0.0.1:5000/send-sms'  # Your webhook server URL
        send_resolved: true
