global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'prom'

rule_files:
  - '/etc/prometheus/rules/*.rules'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'

#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'alertmanager'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['alertmanager:9093']

  # HTTP Monitoring Job
  - job_name: 'http_check'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
          - '/etc/prometheus/http/*.json'
#    static_configs:
#      - targets:
#          - 'https://abin.ir'  # Replace with your web targets
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Ping Monitoring Job
  - job_name: 'icmp_check'
    metrics_path: /probe
    params:
      module: [icmp]  # Use the icmp module for ping probes
    file_sd_configs:
      - files:
          - '/etc/prometheus/icmp/*.json'

#    static_configs:
#      - targets:
#          - '65.21.64.22'
#          - '135.181.129.199'
#          - '94.182.105.88'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
        
  - job_name: 'windows'
    static_configs:
      - targets: ['135.181.129.199:9115']
