apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  editable: true
  isDefault: true
  basicAuth: true
  basicAuthUser: ${PROMETHEUS_USERNAME}
  secureJsonData:
    basicAuthPassword: ${PROMETHEUS_PASSWORD}
